//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ClsDataSets {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_TB_EMP")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_TB_EMP : global::System.Data.DataSet {
        
        private TB_EMPRESADataTable tableTB_EMPRESA;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DS_TB_EMP() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DS_TB_EMP(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TB_EMPRESA"] != null)) {
                    base.Tables.Add(new TB_EMPRESADataTable(ds.Tables["TB_EMPRESA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TB_EMPRESADataTable TB_EMPRESA {
            get {
                return this.tableTB_EMPRESA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DS_TB_EMP cln = ((DS_TB_EMP)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TB_EMPRESA"] != null)) {
                    base.Tables.Add(new TB_EMPRESADataTable(ds.Tables["TB_EMPRESA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTB_EMPRESA = ((TB_EMPRESADataTable)(base.Tables["TB_EMPRESA"]));
            if ((initTable == true)) {
                if ((this.tableTB_EMPRESA != null)) {
                    this.tableTB_EMPRESA.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DS_TB_EMP";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_TB_EMP.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTB_EMPRESA = new TB_EMPRESADataTable();
            base.Tables.Add(this.tableTB_EMPRESA);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeTB_EMPRESA() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_TB_EMP ds = new DS_TB_EMP();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void TB_EMPRESARowChangeEventHandler(object sender, TB_EMPRESARowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TB_EMPRESADataTable : global::System.Data.TypedTableBase<TB_EMPRESARow> {
            
            private global::System.Data.DataColumn columnID;
            
            private global::System.Data.DataColumn columnDS_NOMBRE_EMPRESA;
            
            private global::System.Data.DataColumn columnDS_NOMBRE_CONTACTO;
            
            private global::System.Data.DataColumn columnDS_EMAIL_CONTACTO;
            
            private global::System.Data.DataColumn columnDS_TELEFONO_CONTACTO;
            
            private global::System.Data.DataColumn columnDS_NIT_EMPRESA;
            
            private global::System.Data.DataColumn columnDS_TELEFONO_EMPRESA;
            
            private global::System.Data.DataColumn columnDS_DIRECCION_EMPRESA;
            
            private global::System.Data.DataColumn columnDS_DEPARTAMENTO;
            
            private global::System.Data.DataColumn columnDS_MUNICIPIO;
            
            private global::System.Data.DataColumn columnDS_NOMBRE_REPRESENTANTE;
            
            private global::System.Data.DataColumn columnDS_EMAIL_REPRESENTATE;
            
            private global::System.Data.DataColumn columnDS_NIT_REPRESENTANTE;
            
            private global::System.Data.DataColumn columnDS_DUI_REPRESENTANTE;
            
            private global::System.Data.DataColumn columnDS_ACT_ECO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESADataTable() {
                this.TableName = "TB_EMPRESA";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TB_EMPRESADataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected TB_EMPRESADataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_NOMBRE_EMPRESAColumn {
                get {
                    return this.columnDS_NOMBRE_EMPRESA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_NOMBRE_CONTACTOColumn {
                get {
                    return this.columnDS_NOMBRE_CONTACTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_EMAIL_CONTACTOColumn {
                get {
                    return this.columnDS_EMAIL_CONTACTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_TELEFONO_CONTACTOColumn {
                get {
                    return this.columnDS_TELEFONO_CONTACTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_NIT_EMPRESAColumn {
                get {
                    return this.columnDS_NIT_EMPRESA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_TELEFONO_EMPRESAColumn {
                get {
                    return this.columnDS_TELEFONO_EMPRESA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_DIRECCION_EMPRESAColumn {
                get {
                    return this.columnDS_DIRECCION_EMPRESA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_DEPARTAMENTOColumn {
                get {
                    return this.columnDS_DEPARTAMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_MUNICIPIOColumn {
                get {
                    return this.columnDS_MUNICIPIO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_NOMBRE_REPRESENTANTEColumn {
                get {
                    return this.columnDS_NOMBRE_REPRESENTANTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_EMAIL_REPRESENTATEColumn {
                get {
                    return this.columnDS_EMAIL_REPRESENTATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_NIT_REPRESENTANTEColumn {
                get {
                    return this.columnDS_NIT_REPRESENTANTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_DUI_REPRESENTANTEColumn {
                get {
                    return this.columnDS_DUI_REPRESENTANTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DS_ACT_ECOColumn {
                get {
                    return this.columnDS_ACT_ECO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESARow this[int index] {
                get {
                    return ((TB_EMPRESARow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TB_EMPRESARowChangeEventHandler TB_EMPRESARowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TB_EMPRESARowChangeEventHandler TB_EMPRESARowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TB_EMPRESARowChangeEventHandler TB_EMPRESARowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TB_EMPRESARowChangeEventHandler TB_EMPRESARowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddTB_EMPRESARow(TB_EMPRESARow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESARow AddTB_EMPRESARow(string ID, string DS_NOMBRE_EMPRESA, string DS_NOMBRE_CONTACTO, string DS_EMAIL_CONTACTO, string DS_TELEFONO_CONTACTO, string DS_NIT_EMPRESA, string DS_TELEFONO_EMPRESA, string DS_DIRECCION_EMPRESA, string DS_DEPARTAMENTO, string DS_MUNICIPIO, string DS_NOMBRE_REPRESENTANTE, string DS_EMAIL_REPRESENTATE, string DS_NIT_REPRESENTANTE, string DS_DUI_REPRESENTANTE, string DS_ACT_ECO) {
                TB_EMPRESARow rowTB_EMPRESARow = ((TB_EMPRESARow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ID,
                        DS_NOMBRE_EMPRESA,
                        DS_NOMBRE_CONTACTO,
                        DS_EMAIL_CONTACTO,
                        DS_TELEFONO_CONTACTO,
                        DS_NIT_EMPRESA,
                        DS_TELEFONO_EMPRESA,
                        DS_DIRECCION_EMPRESA,
                        DS_DEPARTAMENTO,
                        DS_MUNICIPIO,
                        DS_NOMBRE_REPRESENTANTE,
                        DS_EMAIL_REPRESENTATE,
                        DS_NIT_REPRESENTANTE,
                        DS_DUI_REPRESENTANTE,
                        DS_ACT_ECO};
                rowTB_EMPRESARow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTB_EMPRESARow);
                return rowTB_EMPRESARow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TB_EMPRESADataTable cln = ((TB_EMPRESADataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TB_EMPRESADataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnID = base.Columns["ID"];
                this.columnDS_NOMBRE_EMPRESA = base.Columns["DS_NOMBRE_EMPRESA"];
                this.columnDS_NOMBRE_CONTACTO = base.Columns["DS_NOMBRE_CONTACTO"];
                this.columnDS_EMAIL_CONTACTO = base.Columns["DS_EMAIL_CONTACTO"];
                this.columnDS_TELEFONO_CONTACTO = base.Columns["DS_TELEFONO_CONTACTO"];
                this.columnDS_NIT_EMPRESA = base.Columns["DS_NIT_EMPRESA"];
                this.columnDS_TELEFONO_EMPRESA = base.Columns["DS_TELEFONO_EMPRESA"];
                this.columnDS_DIRECCION_EMPRESA = base.Columns["DS_DIRECCION_EMPRESA"];
                this.columnDS_DEPARTAMENTO = base.Columns["DS_DEPARTAMENTO"];
                this.columnDS_MUNICIPIO = base.Columns["DS_MUNICIPIO"];
                this.columnDS_NOMBRE_REPRESENTANTE = base.Columns["DS_NOMBRE_REPRESENTANTE"];
                this.columnDS_EMAIL_REPRESENTATE = base.Columns["DS_EMAIL_REPRESENTATE"];
                this.columnDS_NIT_REPRESENTANTE = base.Columns["DS_NIT_REPRESENTANTE"];
                this.columnDS_DUI_REPRESENTANTE = base.Columns["DS_DUI_REPRESENTANTE"];
                this.columnDS_ACT_ECO = base.Columns["DS_ACT_ECO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnID = new global::System.Data.DataColumn("ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
                this.columnDS_NOMBRE_EMPRESA = new global::System.Data.DataColumn("DS_NOMBRE_EMPRESA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NOMBRE_EMPRESA);
                this.columnDS_NOMBRE_CONTACTO = new global::System.Data.DataColumn("DS_NOMBRE_CONTACTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NOMBRE_CONTACTO);
                this.columnDS_EMAIL_CONTACTO = new global::System.Data.DataColumn("DS_EMAIL_CONTACTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_EMAIL_CONTACTO);
                this.columnDS_TELEFONO_CONTACTO = new global::System.Data.DataColumn("DS_TELEFONO_CONTACTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_TELEFONO_CONTACTO);
                this.columnDS_NIT_EMPRESA = new global::System.Data.DataColumn("DS_NIT_EMPRESA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NIT_EMPRESA);
                this.columnDS_TELEFONO_EMPRESA = new global::System.Data.DataColumn("DS_TELEFONO_EMPRESA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_TELEFONO_EMPRESA);
                this.columnDS_DIRECCION_EMPRESA = new global::System.Data.DataColumn("DS_DIRECCION_EMPRESA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_DIRECCION_EMPRESA);
                this.columnDS_DEPARTAMENTO = new global::System.Data.DataColumn("DS_DEPARTAMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_DEPARTAMENTO);
                this.columnDS_MUNICIPIO = new global::System.Data.DataColumn("DS_MUNICIPIO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_MUNICIPIO);
                this.columnDS_NOMBRE_REPRESENTANTE = new global::System.Data.DataColumn("DS_NOMBRE_REPRESENTANTE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NOMBRE_REPRESENTANTE);
                this.columnDS_EMAIL_REPRESENTATE = new global::System.Data.DataColumn("DS_EMAIL_REPRESENTATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_EMAIL_REPRESENTATE);
                this.columnDS_NIT_REPRESENTANTE = new global::System.Data.DataColumn("DS_NIT_REPRESENTANTE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_NIT_REPRESENTANTE);
                this.columnDS_DUI_REPRESENTANTE = new global::System.Data.DataColumn("DS_DUI_REPRESENTANTE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_DUI_REPRESENTANTE);
                this.columnDS_ACT_ECO = new global::System.Data.DataColumn("DS_ACT_ECO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_ACT_ECO);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("TB_EMPRESAKey1", new global::System.Data.DataColumn[] {
                                this.columnID}, false));
                this.columnID.AllowDBNull = false;
                this.columnID.Unique = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESARow NewTB_EMPRESARow() {
                return ((TB_EMPRESARow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TB_EMPRESARow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TB_EMPRESARow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TB_EMPRESARowChanged != null)) {
                    this.TB_EMPRESARowChanged(this, new TB_EMPRESARowChangeEvent(((TB_EMPRESARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TB_EMPRESARowChanging != null)) {
                    this.TB_EMPRESARowChanging(this, new TB_EMPRESARowChangeEvent(((TB_EMPRESARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TB_EMPRESARowDeleted != null)) {
                    this.TB_EMPRESARowDeleted(this, new TB_EMPRESARowChangeEvent(((TB_EMPRESARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TB_EMPRESARowDeleting != null)) {
                    this.TB_EMPRESARowDeleting(this, new TB_EMPRESARowChangeEvent(((TB_EMPRESARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveTB_EMPRESARow(TB_EMPRESARow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_TB_EMP ds = new DS_TB_EMP();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TB_EMPRESADataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TB_EMPRESARow : global::System.Data.DataRow {
            
            private TB_EMPRESADataTable tableTB_EMPRESA;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TB_EMPRESARow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTB_EMPRESA = ((TB_EMPRESADataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ID {
                get {
                    return ((string)(this[this.tableTB_EMPRESA.IDColumn]));
                }
                set {
                    this[this.tableTB_EMPRESA.IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_NOMBRE_EMPRESA {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_NOMBRE_EMPRESAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_NOMBRE_EMPRESA\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_NOMBRE_EMPRESAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_NOMBRE_CONTACTO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_NOMBRE_CONTACTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_NOMBRE_CONTACTO\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_NOMBRE_CONTACTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_EMAIL_CONTACTO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_EMAIL_CONTACTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_EMAIL_CONTACTO\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_EMAIL_CONTACTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_TELEFONO_CONTACTO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_TELEFONO_CONTACTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_TELEFONO_CONTACTO\' de la tabla \'TB_EMPRESA\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_TELEFONO_CONTACTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_NIT_EMPRESA {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_NIT_EMPRESAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_NIT_EMPRESA\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_NIT_EMPRESAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_TELEFONO_EMPRESA {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_TELEFONO_EMPRESAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_TELEFONO_EMPRESA\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_TELEFONO_EMPRESAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_DIRECCION_EMPRESA {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_DIRECCION_EMPRESAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_DIRECCION_EMPRESA\' de la tabla \'TB_EMPRESA\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_DIRECCION_EMPRESAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_DEPARTAMENTO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_DEPARTAMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_DEPARTAMENTO\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_DEPARTAMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_MUNICIPIO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_MUNICIPIOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_MUNICIPIO\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_MUNICIPIOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_NOMBRE_REPRESENTANTE {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_NOMBRE_REPRESENTANTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_NOMBRE_REPRESENTANTE\' de la tabla \'TB_EMPRESA\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_NOMBRE_REPRESENTANTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_EMAIL_REPRESENTATE {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_EMAIL_REPRESENTATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_EMAIL_REPRESENTATE\' de la tabla \'TB_EMPRESA\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_EMAIL_REPRESENTATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_NIT_REPRESENTANTE {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_NIT_REPRESENTANTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_NIT_REPRESENTANTE\' de la tabla \'TB_EMPRESA\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_NIT_REPRESENTANTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_DUI_REPRESENTANTE {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_DUI_REPRESENTANTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_DUI_REPRESENTANTE\' de la tabla \'TB_EMPRESA\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_DUI_REPRESENTANTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DS_ACT_ECO {
                get {
                    try {
                        return ((string)(this[this.tableTB_EMPRESA.DS_ACT_ECOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DS_ACT_ECO\' de la tabla \'TB_EMPRESA\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableTB_EMPRESA.DS_ACT_ECOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_NOMBRE_EMPRESANull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_NOMBRE_EMPRESAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_NOMBRE_EMPRESANull() {
                this[this.tableTB_EMPRESA.DS_NOMBRE_EMPRESAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_NOMBRE_CONTACTONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_NOMBRE_CONTACTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_NOMBRE_CONTACTONull() {
                this[this.tableTB_EMPRESA.DS_NOMBRE_CONTACTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_EMAIL_CONTACTONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_EMAIL_CONTACTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_EMAIL_CONTACTONull() {
                this[this.tableTB_EMPRESA.DS_EMAIL_CONTACTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_TELEFONO_CONTACTONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_TELEFONO_CONTACTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_TELEFONO_CONTACTONull() {
                this[this.tableTB_EMPRESA.DS_TELEFONO_CONTACTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_NIT_EMPRESANull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_NIT_EMPRESAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_NIT_EMPRESANull() {
                this[this.tableTB_EMPRESA.DS_NIT_EMPRESAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_TELEFONO_EMPRESANull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_TELEFONO_EMPRESAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_TELEFONO_EMPRESANull() {
                this[this.tableTB_EMPRESA.DS_TELEFONO_EMPRESAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_DIRECCION_EMPRESANull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_DIRECCION_EMPRESAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_DIRECCION_EMPRESANull() {
                this[this.tableTB_EMPRESA.DS_DIRECCION_EMPRESAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_DEPARTAMENTONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_DEPARTAMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_DEPARTAMENTONull() {
                this[this.tableTB_EMPRESA.DS_DEPARTAMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_MUNICIPIONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_MUNICIPIOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_MUNICIPIONull() {
                this[this.tableTB_EMPRESA.DS_MUNICIPIOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_NOMBRE_REPRESENTANTENull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_NOMBRE_REPRESENTANTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_NOMBRE_REPRESENTANTENull() {
                this[this.tableTB_EMPRESA.DS_NOMBRE_REPRESENTANTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_EMAIL_REPRESENTATENull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_EMAIL_REPRESENTATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_EMAIL_REPRESENTATENull() {
                this[this.tableTB_EMPRESA.DS_EMAIL_REPRESENTATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_NIT_REPRESENTANTENull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_NIT_REPRESENTANTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_NIT_REPRESENTANTENull() {
                this[this.tableTB_EMPRESA.DS_NIT_REPRESENTANTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_DUI_REPRESENTANTENull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_DUI_REPRESENTANTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_DUI_REPRESENTANTENull() {
                this[this.tableTB_EMPRESA.DS_DUI_REPRESENTANTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDS_ACT_ECONull() {
                return this.IsNull(this.tableTB_EMPRESA.DS_ACT_ECOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDS_ACT_ECONull() {
                this[this.tableTB_EMPRESA.DS_ACT_ECOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class TB_EMPRESARowChangeEvent : global::System.EventArgs {
            
            private TB_EMPRESARow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESARowChangeEvent(TB_EMPRESARow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TB_EMPRESARow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591